name: Terraform Plan
description: Run Terraform plan and upload artifact

inputs:
  working-directory:
    required: true
    description: Path to the Terraform project
  unique-suffix:
    required: true
    description: Unique string to append to the artifact name
  credentials:
    required: true
    description: Azure credentials JSON

outputs:
  plan-artifact-name:
    description: Name of the uploaded plan artifact
    value: tfplan-${{ github.run_id }}-${{ github.run_attempt }}-${{ inputs.unique-suffix }}
  plan-exit-code:
    description: Exit code from terraform plan (0=no changes, 1=error, 2=changes)
    value: ${{ steps.plan.outputs.exit-code }}

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ inputs.credentials }}

    - name: Terraform Init
      run: terraform init
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        ARM_CLIENT_ID: ${{ fromJson(inputs.credentials).clientId }}
        ARM_CLIENT_SECRET: ${{ fromJson(inputs.credentials).clientSecret }}
        ARM_TENANT_ID: ${{ fromJson(inputs.credentials).tenantId }}
        ARM_SUBSCRIPTION_ID: ${{ fromJson(inputs.credentials).subscriptionId }}

    - name: Terraform Validate
      run: terraform validate
      shell: bash
      working-directory: ${{ inputs.working-directory }}

    - name: Terraform Plan
      id: plan
      run: |
        set +e
        terraform plan -out=tfplan.binary -input=false -detailed-exitcode
        PLAN_EXIT_CODE=$?
        echo "Terraform plan exit code: $PLAN_EXIT_CODE"
        set -e
        echo "exit-code=$PLAN_EXIT_CODE" >> $GITHUB_OUTPUT
        terraform show -no-color tfplan.binary > tfplan.txt
        case $PLAN_EXIT_CODE in
          0) echo "No changes detected" ;;
          1) echo "Error during plan"; exit 1 ;;
          2) echo "Changes detected" ;;
          *) echo "Unexpected exit code $PLAN_EXIT_CODE"; exit $PLAN_EXIT_CODE ;;
        esac
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        ARM_CLIENT_ID: ${{ fromJson(inputs.credentials).clientId }}
        ARM_CLIENT_SECRET: ${{ fromJson(inputs.credentials).clientSecret }}
        ARM_TENANT_ID: ${{ fromJson(inputs.credentials).tenantId }}
        ARM_SUBSCRIPTION_ID: ${{ fromJson(inputs.credentials).subscriptionId }}

    - name: Upload Plan Artifact
      uses: actions/upload-artifact@v4
      with:
        name: tfplan-${{ github.run_id }}-${{ github.run_attempt }}-${{ inputs.unique-suffix }}
        path: |
          ${{ inputs.working-directory }}/tfplan.txt
          ${{ inputs.working-directory }}/tfplan.binary
