name: Deploy Template
on:
  workflow_call:
    secrets:
      azure_credentials:
        description: 'Azure credentials for Terraform deployment'

jobs:
  plan:
    name: 'Plan'
    uses: ./.github/workflows/terraform-plan.template.yml
    with:
      working-directory: infrastructure
      environment: approval-uat
      unique-suffix: 'example-suffix'
    secrets:
      credentials: ${{ secrets.AZURE_CREDENTIALS }}

  apply:
    name: 'Apply'
    needs: plan
    uses: ./.github/workflows/terraform-apply.template.yml
    with:
      working-directory: infrastructure
      environment: approval-uat
      plan-artifact-name: ${{ needs.plan.outputs.plan-artifact-name }}
    secrets:
      credentials: ${{ secrets.AZURE_CREDENTIALS }}