name: (template) deploy.template.yml

on:
  workflow_call:
    inputs:
      github-environment:
        required: true
        type: string
        description: The GitHub environment to deploy to
      environment:
        required: true
        type: string
        description: The environment to deploy to
    secrets:
      azure_service_connection:
        required: true
        description: Azure credentials JSON for Terraform operations

permissions:
  issues: write
  contents: read

jobs:
  deploy:
    environment: ${{ inputs.github-environment }}
    name: 'Deploy'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Terraform Plan
        id: plan
        uses: ./.github/actions/terraform/plan
        with:
          working-directory: infrastructure
          unique-suffix: ${{ inputs.environment }}
          credentials: ${{ secrets.azure_service_connection }}

      - name: Download Terraform Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan-${{ github.run_id }}-${{ github.run_attempt }}-${{ inputs.environment }}
          path: ./tfplan-artifact

      - name: Output Terraform Plan to Summary
        run: |
          echo "## Terraform Plan" >> $GITHUB_STEP_SUMMARY
          head -20 ./tfplan-artifact/tfplan.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

      - name: Manual approval
        if: steps.plan.outputs.plan-exit-code == '2'
        uses: ./.github/actions/terraform/review
        with:
          secret: ${{ github.token }}
          approvers: ${{ github.actor }}
          working-directory: infrastructure
          minimum-approvals: 1
          issue-title: "Review Terraform Plan for Deployment - ${{ inputs.environment }} - ${{ github.ref_name }}"
          issue-body-file-path: .github/approvals/test.md
          plan-artifact-name: tfplan-${{ github.run_id }}-${{ github.run_attempt }}-${{ inputs.environment }}
          exclude-workflow-initiator-as-approver: false
          fail-on-denial: true
          additional-approved-words: ''
          additional-denied-words: ''

      - name: Terraform Apply
        uses: ./.github/actions/terraform/apply
        with:
          working-directory: infrastructure
          plan-artifact-name: tfplan-${{ github.run_id }}-${{ github.run_attempt }}-${{ inputs.environment }}
          credentials: ${{ secrets.azure_service_connection }}