name: (template) dev.template.yml

on:
  workflow_call:

permissions:
  issues: write
  contents: read

jobs:
  deploy-dev:
    name: 'Dev'
    uses: ./.github/workflows/deploy.template.yml
    with:
      github-environment: dev
      environment: dev
    secrets:
      azure_service_connection: ${{ secrets.AZURE_CREDENTIALS }}
