name: Deploy

on:
  workflow_dispatch:

permissions:
  issues: write
  contents: read

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Terraform Plan
        uses: ./.github/actions/terraform/plan
        with:
          working-directory: infrastructure
          unique-suffix: dev
          credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Manual approval
        uses: ./.github/actions/terraform/review
        with:
          secret: ${{ github.token }}
          approvers: 11bthornton
          minimum-approvals: 1
          issue-title: "Deploying v1.3.5 to prod from staging"
          issue-body-file-path: .github/approvals/test.md
          exclude-workflow-initiator-as-approver: false
          fail-on-denial: true
          additional-approved-words: ''
          additional-denied-words: ''

      - name: Terraform Apply
        uses: ./.github/actions/terraform/apply
        with:
          working-directory: infrastructure/dev
          plan-artifact-name: tfplan-${{ github.run_id }}-${{ github.run_attempt }}-dev
          credentials: ${{ secrets.AZURE_CREDENTIALS }}