name: Terraform Plan

on:
  workflow_dispatch:

jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Terraform Plan
        uses: ./.github/actions/terraform/plan
        with:
          working-directory: infrastructure/dev
          unique-suffix: dev
          credentials: ${{ secrets.AZURE_CREDENTIALS }}
