name: Terraform Plan

on:
  workflow_dispatch:

jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Terraform Plan
        uses: ./.github/actions/terraform/plan
        with:
          working-directory: infrastructure
          unique-suffix: dev
          credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Apply
        uses: ./.github/actions/terraform-apply
        with:
          working-directory: infrastructure/dev
          plan-artifact-name: tfplan-${{ github.run_id }}-${{ github.run_attempt }}-dev
          credentials: ${{ secrets.AZURE_CREDENTIALS }}