name: Terraform Plan for PR

on:
  pull_request:
    paths:
      - 'infrastructure/**'
    branches:
      - main

jobs:
  plan:
    uses: ./.github/workflows/terraform-plan.yml
    with:
      working-directory: infrastructure
      environment: production
    secrets:
      credentials: ${{ secrets.AZURE_CREDENTIALS }}
