name: (pull request) pr.tf-plan.yml

on:
  pull_request:
    branches:
      - main

permissions:
  issues: write
  contents: read
  pull-requests: write
  actions: read

jobs:
  tf-plan:
    name: 'Terraform Plan'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Terraform Plan
        uses: ./.github/actions/terraform/plan
        with:
          working-directory: ./infrastructure
          unique-suffix: uat
          credentials: ${{ secrets.AZURE_CREDENTIALS }}