name: (template) prod.template.yml

on:
  workflow_call:

permissions:
  issues: write
  contents: read

jobs:
  deploy-prod:
    name: 'Prod'
    uses: ./.github/workflows/deploy.template.yml
    with:
      github-environment: prod
      environment: prod
    secrets:
      azure_service_connection: ${{ secrets.AZURE_CREDENTIALS }}
