name: Terraform Plan Reusable Workflow

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
      environment:
        required: false
        type: string
        default: ""
      unique-suffix:
        required: true
        type: string
    secrets:
      credentials:
        required: true
    outputs:
      plan-artifact-name:
        description: "Name of the plan artifact"
        value: ${{ jobs.terraform-plan.outputs.plan-artifact-name }}

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    outputs:
      plan-artifact-name: ${{ steps.artifact.outputs.artifact-name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.credentials }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -out=tfplan.binary -input=false
          terraform show -no-color tfplan.binary > tfplan.txt

      - name: Upload Plan Artifact
        id: artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ github.run_id }}-${{ github.run_attempt }}
          path: |
            ${{ inputs.working-directory }}/tfplan.txt
            ${{ inputs.working-directory }}/tfplan.binary
        env:
          ARTIFACT_NAME: tfplan-${{ github.run_id }}-${{ github.run_attempt }}-${{ inputs.unique-suffix }}
