name: (template) uat.template.yml

on:
  workflow_dispatch:

permissions:
  issues: write
  contents: read

jobs:
  deploy-uat:
    name: 'UAT'
    uses: ./.github/workflows/deploy.template.yml
    with:
      github-environment: uat
      environment: uat
    secrets:
      azure_service_connection: ${{ secrets.AZURE_CREDENTIALS }}
